name: 'Run Unit Tests'
description: 'Reusable action to run unit tests in uv or poetry environments.'
runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash
      run: |
        if [ -f "uv.lock" ]; then
          uv run pytest
        else
          poetry run pytest
        fi
