name: 'Run Unit Tests'
description: 'Reusable action to setup python, poetry and project dependencies in a standard way.'
runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash
      run: poetry run pytest
