name: Create Release
description: Reusable action to create Python releases.
inputs:
  GEMFURY_DEPLOY_TOKEN:
    description: Gemfury Deploy Token
    required: true
  release-branch:
    required: false
    default: ''
    description: Branch to open pull release PR against (defaults to repo default branch if not specified).
outputs:
  created-release:
    description: true if a versioned release was created (false if only made release candidate PR)
    value: ${{ steps.release.outputs.release_created }}
runs:
  using: composite
  steps:
    - uses: ./.reusable-workflows/py-run-tests
      with:
        GEMFURY_DEPLOY_TOKEN: ${{ inputs.GEMFURY_DEPLOY_TOKEN }}
    - name: Install tomlkit
      # Ensure tomlkit is installed, so I can retrieve package info on next step.
      # In Python 3.11, there is now a built-in `tomllib` library we can use.
      # Once everything is on Python 3.11, we can change this code to use `tomllib` instead.
      shell: bash
      run: poetry run pip install tomlkit
    - name: Retrieve Project Package via tomlkit
      shell: bash
      run: |
        PY_OUTPUT=$(poetry run -q python -c "import tomlkit; import pathlib; print(tomlkit.parse(pathlib.Path('pyproject.toml').read_text())['tool']['poetry']['name'], end='')")
        echo "PY_Z_MODULE=$PY_OUTPUT" | tr - _ >> $GITHUB_ENV

    - name: Copy + Configure .versionrc.json File...
      shell: bash
      run: |
        cp .reusable-workflows/versionsrc-config/python.versionrc.json .versionrc.json
        echo "`jq '.bumpFiles[2].filename="'$PY_Z_MODULE'/__init__.py"' .versionrc.json`" > .versionrc.json
      env:
        PY_Z_MODULE: ${{ env.PY_Z_MODULE }}
#    - name: (debug + failure) Setup SSH Session
#      uses: mxschmitt/action-tmate@v3
#    #        if: ${{ runner.debug == 1 }}
#      with:
#        timeout-minutes: 20
#        limit-access-to-actor: true
    - uses: ./.reusable-workflows/all-commit-and-tag-release

#      id: release
#      with:
#        release-type: python
#        package-name: ${{ env.PY_PKG }}
#        default-branch: ${{ inputs.release-branch }}
