name: Create Release
description: Reusable action to create Python releases.
outputs:
  created-release-tag-name:
    description: Tag name of the created release
    value: ${{ steps.release.outputs.created-release-tag-name }}
runs:
  using: composite
  steps:
    - name: Configure .versionrc.json File with Poetry
      if: env.PKG_MANAGER == 'poetry'
      shell: bash
      run: poetry run -q python .reusable-workflows/versionsrc-config/python-versionrc.py

    - name: Configure .versionrc.json File with UV
      if: env.PKG_MANAGER == 'uv'
      shell: bash
      run: uv run -q python .reusable-workflows/versionsrc-config/python-versionrc.py

    - uses: ./.reusable-workflows/all-commit-and-tag-release
      id: release
