name: Deploy Python via Serverless
description: Reusable action to deploy Python via the Serverless Framework.
inputs:
  GEMFURY_PUBLISH_TOKEN:
    description: Gemfury Publish Token
    required: true
runs:
  using: composite
  steps:
    - name: Build Library
      shell: bash
      run: poetry build
    - name: Publish to Gemfury
      shell: bash
      run: |
        poetry config http-basic.fury ${{inputs.GEMFURY_PUBLISH_TOKEN}} NOPASS
        poetry publish -r fury
