name: 'Setup Python and Project Deps (Poetry or UV)'
description: 'Wrapper action that delegates to poetry/ or uv/ composite actions.'
inputs:
  GEMFURY_DEPLOY_TOKEN:
    description: Gemfury Deploy Token
    required: true
runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #       Detect Package Manager And Setup
    #----------------------------------------------
    - name: Detect Package Manager
      shell: bash
      run: |
        if [ -f "uv.lock" ]; then
          echo "Detected package manager: uv (ver 0.8)"
          echo "PKG_MANAGER=uv" >> "$GITHUB_ENV"
        else
          echo "Detected package manager: poetry"
          echo "PKG_MANAGER=poetry" >> "$GITHUB_ENV"
        fi

    - name: Setup with Poetry
      if: env.PKG_MANAGER == 'poetry'
      uses: ./.reusable-workflows/py-setup-project/poetry
      with:
        GEMFURY_DEPLOY_TOKEN: ${{ inputs.GEMFURY_DEPLOY_TOKEN }}

    - name: Setup with UV
      if: env.PKG_MANAGER == 'uv'
      uses: ./.reusable-workflows/py-setup-project/uv
      with:
        GEMFURY_DEPLOY_TOKEN: ${{ inputs.GEMFURY_DEPLOY_TOKEN }}
