name: 'Setup Python, Poetry and Project Deps'
description: 'Reusable action to setup python, poetry and project dependencies in a standard way.'
runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #       Check-out repo, set-up python + poetry
    #----------------------------------------------
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install poetry
      shell: bash
      run: pipx install poetry
    - name: Read Needed Python Version
      shell: bash
      run: |
        PY_VER=$(sed -n 's/^ *python *= *"[~^]*\([0-9\.]*\)"/\1/p' pyproject.toml)
        echo "PY_VERSION=$PY_VER" >> $GITHUB_ENV
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PY_VERSION }}
        cache: poetry
    #----------------------------------------------
    #         Install dependencies + self
    #----------------------------------------------
    - name: Install Dependencies
      shell: bash
      run: poetry install --no-interaction --no-root
    - name: Install Self
      shell: bash
      run: poetry install --no-interaction
