name: 'Setup Python with UV'
description: 'Setup python, uv and project dependencies using uv sync --frozen.'
inputs:
  GEMFURY_DEPLOY_TOKEN:
    description: Gemfury Deploy Token
    required: true
runs:
  using: "composite"
  steps:
    - name: Read Needed Python Version
      shell: bash
      run: |
        PY_VER=$(sed -n 's/^ *requires-python *= *"==\([0-9]*\.[0-9]*\).*/\1/p' pyproject.toml)
        echo "PY_VERSION=$PY_VER" >> "$GITHUB_ENV"

    - name: Setup Python v${{ env.PY_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PY_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: 0.11.23

    - name: Login to GemFury
      shell: bash
      env:
        GEMFURY_TOKEN: ${{ inputs.GEMFURY_DEPLOY_TOKEN }}
      run: uv auth login --username ${{ inputs.GEMFURY_DEPLOY_TOKEN }} --password NOPASS https://pypi.fury.io/zerapix

    - name: Install ZP
      shell: bash
      run: uv tool install --force --index=https://pypi.fury.io/zerapix zp@1.17.2

    - name: Log ZP Version
      shell: bash
      run: zp --version

    - name: Install UV Dependencies
      shell: bash
      run: uv sync --frozen --no-dev


