name: Deploy Python via Serverless
description: Reusable action to deploy Python via the Serverless Framework.
inputs:
  environment:
    description: Environmental name to deploy in.
    required: true
runs:
  using: composite
  steps:
    #----------------------------------------------
    # Install serverless framework and deploy
    #----------------------------------------------
    - name: Setup Node.js
      id: setup_node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: "yarn"
    - name: Install Yarn/Serverless Deps Into ${{ steps.setup_node.outputs.node-version }}
      run: yarn install --frozen-lockfile
      shell: bash
    - name: Serverless Deploy to dev
      # Hard-coding the environment for now, when we start dealing with other environments
      # look into environment feature of github actions/workflows.
      run: yarn sls deploy --verbose --stage ${{ inputs.environment }}
      shell: bash
