# This workflow runs CodeQL analysis to scan Python code for security and quality issues.
on:
  workflow_call:

name: Analyze Python Code
run-name: Analyze JS Code for @${{ github.actor }}
defaults:
  run:
    shell: bash

jobs:
  analyze:
    uses: zerapix/reusable-workflows/.github/workflows/js-deploy-w-sls.yml
    secrets: inherit
    with:
      lang: js

