name: 'Setup Node and Yarn Project Deps'
description: 'Reusable action to setup node and yarn.'
inputs:
  fetch-depth:
    # Defaults to only current, use "0" to fetch all history for use by version bumper.
    description: Git Fetch Depth
    default: '1'
runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #       Set-up node + yarn
    #----------------------------------------------
    - name: Setup Node.js
      id: setup_node
      uses: actions/setup-node@v6
      with:
        node-version: "24"
        cache: "yarn"
    - name: Enable corepack
      run: corepack enable
      shell: bash
    - name: Set yarn Version
      run: yarn set version 4.17.1
      shell: bash
    - name: Install Yarn/Serverless Deps Into ${{ steps.setup_node.outputs.node-version }}
      # # Would like to run with `--frozen-lockfile`, but I think updating the version number makes the yarn installer
      # # think a big enough change happened to the package.json that it can't do a `--frozen-lockfile` anymore.
      # # TODO: Investigate using a `--frozen-lockfile` option someday for yarn in combination with version/release creation.
      # run: yarn install --frozen-lockfile
      run: yarn install
      shell: bash
    - name: Finished Echo
      run: echo "Finished installing deps..."
      shell: bash
