name: 'Setup Node and Yarn Project Deps'
description: 'Reusable action to checkout project'
runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #       Check-out repo, set-up node + yarn
    #----------------------------------------------
    # ln -s /home/runner/work/_actions/./.reusable-workflows/test .reusable-workflows

    - name: Checkout Project Repo
      uses: actions/checkout@v6
    # When you use an action from a repo, github will do a local checkout of the repo
    # to a specific location. Instead of checking out the repo twice, using sym-link to already
    # checkout version (plus when building things, it's just a symlink and so hopefully avoids
    # (accidentally included files from the reusable-workflows repo in the deployments).
    - name: Symlink Reusable Workflows
      shell: bash
      run: ln -s ${{ github.action_path }}/.. .reusable-workflows

