name: 'Setup Node and Yarn Project Deps'
description: 'Reusable action to setup node and yarn.'
inputs:
  fetch-depth:
    # Defaults to only current, use "0" to fetch all history for use by version bumper.
    description: Git Fetch Depth
    default: '1'
  reusable-ref:
    default: main
    description: Reusable workflow branch/tag/etc I am being called in.
  zreleasebot_app_id:
    description: zReleaseBot - from org secrets - App ID
  zreleasebot_private_key:
    description: zReleaseBot - from org secrets - Private Key (used to sign the JWT)
runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #       Check-out repo, set-up node + yarn
    #----------------------------------------------
    # ln -s /home/runner/work/_actions/zerapix/reusable-workflows/test .reusable-workflows
    - name: Symlink Reusable Workflows
      shell: bash
      run: ln -s /home/runner/work/_actions/zerapix/reusable-workflows/${{ inputs.reusable-ref }} .reusable-workflows
    - name: zReleaseBot Token
      id: my-app
      uses: getsentry/action-github-app-token@v2
      with:
        app_id: ${{ inputs.ZRELEASEBOT_APP_ID }}
        private_key: ${{ inputs.ZRELEASEBOT_PRIVATE_KEY }}
    - name: Checkout Project Repo
      uses: actions/checkout@v4
      with:
        # fetch-depth 0 will check out all the commits and tags needed for release-bumper
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ steps.my-app.outputs.token }}
#    - name: Checkout Reusable Repo
#      uses: actions/checkout@v4
#      with:
#        repository: zerapix/reusable-workflows
#        path: repos/reusable-workflows
#        ref: ${{ inputs.reusable-ref }}
#        token: ${{ steps.my-app.outputs.token }}
