# This workflow is used to run unit tests without a DB.
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
        description: Defaults to x64; specify to use a different runner.
      dev-app-host:
        type: string
        description: Host name to link to (will prepend 'prs*' to start of host).
        required: false
        default: ''
      lang:
        type: string
        description: Main project language, currently either `py` or `js`.
        required: true
      need-testing-db:
        type: boolean
        default: false
        description: If DB service is needed for testing.
defaults:
  run:
    shell: bash
name: Test

jobs:
  get-prs-slot:
    # We want the prs slot number finder/getter to one run one at a time.
    runs-on: ${{ inputs.runs-on }}
    concurrency: get-prs-slot
    if: ${{ inputs.lang == 'js' }}
    outputs:
      slot-num: ${{ steps.slot-num.outputs.result }}
    steps:
      - name: Deploying PR ${{ github.event.number }}
        run: echo Attached To PR ${{ github.event.number }}
        shell: bash
#      # When you use an action from a repo, github will do a local checkout of the repo
#      # to a specific location. Instead of checking out the repo twice, using sym-link to already
#      # checkout version (plus when building things, it's just a symlink and so hopefully avoids
#      # (accidentally included files from the reusable-workflows repo in the deployments).
#      - name: Symlink Reusable Workflows
#        shell: bash
#        run: ln -s ${{ github.action_path }}/.. .reusable-workflows

      - uses: zerapix/reusable-workflows/all-checkout@test
      # # These seem unneeded, we just need the slot-number,
      # # and we want that to go as fast as possible.
      # - uses: zerapix/reusable-workflows/all-checkout@test
      # - uses: ./.reusable-workflows/js-setup-project

      # Get/Assign the prs* stage name for pr.
      - uses: actions/github-script@v7
        id: slot-num
        with:  # "pixydocs.dev.zerapix.com"
          script: |
            const script = require('./.reusable-workflows/scripts/get-pr-slot.js')
            const devAppHost = '${{ inputs.dev-app-host }}'
            return script({github, context, devAppHost})
      - run: echo "Assigned PR Slot (${{ steps.slot-num.outputs.result }})."

  js-test:
    if: ${{ inputs.lang == 'js' }}
    needs: get-prs-slot
    secrets: inherit
    uses: zerapix/reusable-workflows/.github/workflows/all-deploy.yml@test
    with:
      environment: 'prs'
      override-stage-name: 'prs${{ needs.get-prs-slot.outputs.slot-num }}'
      pre-release: true
      runs-on: ${{ inputs.runs-on }}
      lang: ${{ inputs.lang }}

  py-test:
    runs-on: ${{ inputs.runs-on }}
    if: ${{ inputs.lang == 'py' && !inputs.need-testing-db }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: zerapix/reusable-workflows/all-checkout@test
      - uses: ./.reusable-workflows/py-setup-project
        with:
          GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}
      - name: Setup and Test Project
        uses: ./.reusable-workflows/py-run-tests

  py-test-w-db:
    runs-on: ${{ inputs.runs-on }}
    if: ${{ inputs.lang == 'py' && inputs.need-testing-db }}
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-pass
      POSTGRES_DB: unitTestingDB-unit
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    steps:
      - uses: zerapix/reusable-workflows/all-checkout@test
      - uses: ./.reusable-workflows/py-setup-project
        with:
          GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}
      - name: Setup and Test Project
        uses: ./.reusable-workflows/py-run-tests
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pg-pass
          POSTGRES_DB: pixyDocsApi-unknown
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 15432:5432

#  # We now automatically analyze code for any PR that targets the main branch; so this is duplicative now.
#  analyze:
#    uses: zerapix/reusable-workflows/.github/workflows/py-analyze.yml@test
#    secrets: inherit
