name: Deploy To Environment
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
        description: Environment to deploy in.

      override-stage-name:
        required: false
        type: string
        default: ''
        description: Defaults to the environment name; use this if the stage is different; like if its an account-wide "all" stage.

      runs-on:
        required: false
        type: string
        default: ubuntu-latest
        description: Defaults to x64; specify to use a different runner.

      pre-release:
        type: boolean
        default: false
        description: Set to true if you want to set a pre-release version for deployment.

      lang:
        type: string
        description: Main project language, currently either `py` or `js`.
defaults:
  run:
    shell: bash

concurrency: deploy-${{ inputs.environment }}-${{ inputs.override-stage-name }}

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: zerapix/reusable-workflows/all-checkout@test

      - uses: ./.reusable-workflows/js-setup-project
        if: ${{ lang == 'js' }}

      - uses: ./.reusable-workflows/py-setup-project
        with:
          GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}

        # Setup pre-release version string on package if needed
        # Example Pre-Release Version String: "0.1.34-3-g90111b9"
        # Format: {last-version-tag}-{num-commits-since-version-tag}-{git-hash}
      - name: Set Pre-Release Version
        if: ${{ inputs.lang == 'js' && inputs.pre-release }}
        run: yarn version --no-git-tag-version --new-version "$( (git describe --tags --long | tr -d " v\n\t\r") )"

      - uses: ./.reusable-workflows/all-deploy-sls
        with:
          environment: ${{ inputs.environment }}
          override-stage-name: ${{ inputs.override-stage-name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
