# Normally called on pull_request events
on:
  workflow_call:
    inputs:
      dev-app-host:
        type: string
        description: Host name to link to (will prepend 'prs*' to start of host).
        required: true

concurrency: deploy-pr-${{ github.event.number }}
name: Deploy PR

jobs:
  get-prs-slot:
    runs-on: ubuntu-latest
    outputs:
      slot-num: ${{ steps.slot-num.outputs.result }}
    steps:
      - name: Deploying PR ${{ github.event.number }}
        run: echo Attached To PR ${{ github.event.number }}
      - uses: zerapix/reusable-workflows/all-checkout@test
      - uses: ./.reusable-workflows/js-setup-project

      # Get/Assign the prs* stage name for pr.
      - uses: actions/github-script@v6
        id: slot-num
        with:  # "pixydocs.dev.zerapix.com"
          script: |
            const script = require('./.reusable-workflows/scripts/get-pr-slot.js')
            const devAppHost = '${{ inputs.dev-app-host }}'
            return script({github, context, devAppHost})
      - run: echo "Assigned PR Slot (${{ steps.slot-num.outputs.result }})."

  deploy-prs:
    needs: get-prs-slot
    uses: ./.reusable-workflows/.github/workflows/js-deploy-w-sls.yml
    secrets: inherit
    with:
      environment: 'prs'
      override-stage-name: 'prs${{ needs.get-prs-slot.outputs.slot-num }}'
      pre-release: true
