name: Deploy To Environment
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
        description: Environment to deploy in.

      override-stage-name:
        required: false
        type: string
        default: ''
        description: Defaults to the environment name; use this if the stage is different; like if its an account-wide "all" stage.

      reusable-ref:
        type: string
        default: main
        description: Reusable workflow branch/tag/etc I am being called in.
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    concurrency: deploy-${{ inputs.environment }}
    steps:
      - run: echo "Deploying For Environment ${{ inputs.environment }}; Ref ${{ github.ref }}"

      - uses: zerapix/reusable-workflows/all-checkout@test
        with:
          # fetch-depth 0 will check out all the commits and tags needed for release-bumper
          fetch-depth: 0
          reusable-ref: ${{ inputs.reusable-ref }}

      #----------------------------------------------
      #       Only Check-out repo for now...
      #
      #       all-deploy-sls action will do everything else we need
      #       for the moment; at some point we may want to do unit-testing here
      #       and if that's the case then we need to pass a flag to deployment action to skip
      #       setting up node/yarn again.
      #----------------------------------------------
      - uses: zerapix/reusable-workflows/all-deploy-sls@test
        with:
          environment: ${{ inputs.environment }}
          override-stage-name: ${{ inputs.override-stage-name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
