# Normally called on pull_request events
on:
  workflow_call:
    inputs:
      reusable-ref:
        type: string
        default: main
        description: Reusable workflow branch/tag/etc I am being called in.

      dev-app-host:
        type: string
        description: Host name to link to (will prepend 'prs*' to start of host).
        required: true

      dev-app-pd-host:
        type: string
        description: PD host name to link to (will prepend 'prs*' to start of host).
        default: 'app.pixydocs.dev'

concurrency: deploy-pr-${{ github.event.number }}
name: Deploy PR

jobs:
  get-prs-slot:
    runs-on: ubuntu-latest
    outputs:
      slot-num: ${{ steps.slot-num.outputs.result }}
    steps:
      - name: Deploying PR ${{ github.event.number }}
        run: echo Attached To PR ${{ github.event.number }}
      - uses: zerapix/reusable-workflows/all-checkout@main
        with:
          reusable-ref: ${{ inputs.reusable-ref }}
      - uses: ./.reusable-workflows/js-setup-project

      # Get/Assign the prs* stage name for pr.
      - uses: actions/github-script@v6
        id: slot-num
        with:  # "pixydocs.dev.zerapix.com"
          script: |
            const script = require('./.reusable-workflows/scripts/get-pr-slot.js')
            const devAppHost = '${{ inputs.dev-app-host }}'
            const devPdAppHost = '${{ inputs.dev-app-pd-host }}'
            return script({github, context, devAppHost, devPdAppHost})
      - run: echo "Assigned PR Slot (${{ steps.slot-num.outputs.result }})."

  deploy-prs:
    needs: get-prs-slot
    uses: zerapix/reusable-workflows/.github/workflows/js-deploy-w-sls.yml@main
    secrets: inherit
    with:
      environment: 'prs'
      override-stage-name: 'prs${{ needs.get-prs-slot.outputs.slot-num }}'
      pre-release: true
      reusable-ref: ${{ inputs.reusable-ref }}
