name: Deploy To Environment
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
        description: Environment to deploy in.

      override-stage-name:
        required: false
        type: string
        default: ''
        description: Defaults to the environment name; use this if the stage is different; like if its an account-wide "all" stage.

      reusable-ref:
        type: string
        default: main
        description: Reusable workflow branch/tag/etc I am being called in.

      pre-release:
        type: boolean
        default: false
        description: Set to true if you want to set a pre-release version for deployment.
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    concurrency: deploy-${{ inputs.environment }}-${{ inputs.override-stage-name }}
    steps:
      - run: echo "Deploying For Environment ${{ inputs.environment }}; Ref ${{ github.ref }}"

      - uses: zerapix/reusable-workflows/all-checkout@test
        with:
          # fetch-depth 0 will check out all the commits and tag history.
          fetch-depth: 0
          reusable-ref: ${{ inputs.reusable-ref }}
      - uses: ./.reusable-workflows/js-setup-project

      # Setup pre-release version string on package if needed
      # Example Pre-Release Version String: "0.1.34-3-g90111b9"
      # Format: {last-version-tag}-{num-commits-since-version-tag}-{git-hash}
      - name: Set Pre-Release Version
        if: ${{ inputs.pre-release }}
        run: yarn version --no-git-tag-version --new-version "$( (git describe --tags --long | tr -d " v\n\t\r") )"

      #----------------------------------------------
      #       Only Check-out repo for now...
      #
      #       all-deploy-sls action will do everything else we need
      #       for the moment; at some point we may want to do unit-testing here
      #       and if that's the case then we need to pass a flag to deployment action to skip
      #       setting up node/yarn again.
      #----------------------------------------------
      - uses: zerapix/reusable-workflows/all-deploy-sls@test
        with:
          environment: ${{ inputs.environment }}
          override-stage-name: ${{ inputs.override-stage-name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
