# Normally called when a merge to the main branch happens.
on:
  workflow_call:
name: merge-to-main-release-please
jobs:
  create-release:
    concurrency: create-release
    runs-on: ubuntu-latest
    # If are already on a 'release' commit, we should skip this job.
    if: "!startsWith(github.event.head_commit.message, 'chore(release): ')"
    steps:
      - uses: zerapix/reusable-workflows/js-setup-project@test
        with:
          GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}
          fetch-depth: '0'
      - run: echo Running On Ref ${{ github.ref }}
      - name: Increment, Tag and Commit for Release
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an) (action)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          yarn commit-and-tag-version
          git push --follow-tags origin main
      - name: Get Tag Name
        id: tag-out
        run: |
          tag_name=$( (git describe --tags --abbrev=0 | tr -d " \n\t\r") )
          echo "Using Tag Name: $tag_name"
          echo "value=$tag_name" >> $GITHUB_OUTPUT
      - name: Get Changelog
        id: change-log
        run: |
          change_log="$(git diff --unified=0 --color-words --no-prefix HEAD~1 HEAD -- CHANGELOG.md  | perl -wlne 'print $1 if /^\e\[32m(.*)\e\[m$/')"
          echo "Using Change Log: $change_log"
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "value<<$EOF" >> $GITHUB_ENV
          echo "$change_log" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        id: create-release
        with:
          tag_name: refs/tags/${{ steps.tag-out.outputs.value }}
          name: ${{ steps.tag-out.outputs.value }}
          generate_release_notes: false
          body: ${{ steps.change-log.outputs.value }}
      - name: Link From PR to Release
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Released As: ${{ steps.tag-out.outputs.value }}, ${{ steps.create-release.outputs.url }}
#  # Create Separate Job, to distinguish release-creation from deployment
#  # (release could have succeeded but deployment fail, can easily re-run deployment without running create-release again)
#  deploy-release:
#    needs: create-release
#    runs-on: ubuntu-latest
#    environment: ${{ inputs.auto-release-environment }}
#    concurrency: deploy-dev
#    steps:
#      - uses: zerapix/reusable-workflows/py-setup-project@test
#      - uses: zerapix/reusable-workflows/py-deploy-serverless@test
#        with:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

