# Normally called when a merge to the main branch happens.
on:
  workflow_call:
name: merge-to-main-release-please
jobs:
  create-release:
    concurrency: create-release
    runs-on: ubuntu-latest
    # If are already on a 'release' commit, we should skip this job.
    if: "!startsWith(github.event.head_commit.message, 'chore(release): ')"
    steps:
      - uses: zerapix/reusable-workflows/js-setup-project@test
        with:
          GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}
          fetch-depth: '0'
      - run: echo BEFORE ${{ github.ref }}
      - name: Increment, Tag and Commit for Release
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an) (action)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          yarn commit-and-tag-version
          git push --follow-tags origin main
      - run: echo AFTER ${{ github.ref }}

#  # Create Separate Job, to distinguish release-creation from deployment
#  # (release could have succeeded but deployment fail, can easily re-run deployment without running create-release again)
#  deploy-release:
#    needs: create-release
#    runs-on: ubuntu-latest
#    environment: ${{ inputs.auto-release-environment }}
#    concurrency: deploy-dev
#    steps:
#      - uses: zerapix/reusable-workflows/py-setup-project@test
#      - uses: zerapix/reusable-workflows/py-deploy-serverless@test
#        with:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

