# This workflow runs CodeQL analysis to scan Python code for security and quality issues.
on:
  workflow_call:

name: Analyze Python Code
run-name: Analyze Python Code for @${{ github.actor }}
defaults:
  run:
    shell: bash

jobs:
  redirect:
    uses: zerapix/reusable-workflows/.github/workflows/all-analyze.yml@test
    secrets: inherit
    with:
      lang: py
