# Creates a release; if you want to use this in other projects a better start is probably
# one of the py-merge-to-main-* workflows (which in turn can use this reusable workflow).
on:
  workflow_call:
    inputs:
      need-testing-db:
        type: boolean
        default: false
        description: If DB service is needed for testing.
run-name: Create Release + Auto Deploy by @${{ github.actor }}
name: Create Release
jobs:
  redirect:
    uses: zerapix/reusable-workflows/.github/workflows/all-create-release.yml@test
    secrets: inherit
    with:
      need-testing-db: ${{ inputs.need-testing-db }}
      lang: py
