# Creates a release; if you want to use this in other projects a better start is probably
# one of the py-merge-to-main-* workflows (which in turn can use this reusable workflow).
on:
  workflow_call:
    inputs:
      need-testing-db:
        type: boolean
        default: false
        description: If DB service is needed for testing.
defaults:
  run:
    shell: bash
concurrency: create-release
run-name: Create Release + Auto Deploy by @${{ github.actor }}

name: Create Release
jobs:
  release:
    uses: zerapix/reusable-workflows/.github/workflows/py-create-release.yml@test
    with:
      lang: py
