name: Deploy To Environment
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
        description: Environment to deploy in.

      override-stage-name:
        required: false
        type: string
        default: ''
        description: Defaults to the environment name; use this if the stage is different; like if its an account-wide "all" stage.

      runs-on:
        required: false
        type: string
        default: ubuntu-latest
        description: Defaults to x64; specify to use a different runner.

jobs:
  redirect:
    uses: zerapix/reusable-workflows/.github/workflows/all-deploy.yml@test
    secrets: inherit
    with:
      lang: py
      runs-on: ${{ inputs.runs-on }}
      environment: ${{ inputs.environment }}
      override-stage-name: ${{ inputs.override-stage-name }}
