# Normally called when a merge to the main branch happens.
on:
  workflow_call:
name: merge-to-main-release-please
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      created-release: ${{ steps.release.outputs.created-release }}
    steps:
      - uses: zerapix/reusable-workflows/py-create-release@test
        id: release
        with:
          GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}
          release-branch: ${{ inputs.release-branch }}

  # Create Separate Job, to distinguish release-creation from publishing
  # (release could have succeeded but deployment fail, can easily re-run deployment without running create-release again)
  publish-release:
    needs: create-release
    runs-on: ubuntu-latest
    concurrency: publish-dev
    if: ${{ needs.create-release.outputs.created-release }}
    steps:
      - uses: zerapix/reusable-workflows/py-setup-project@test
        with:
          GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}
      - uses: zerapix/reusable-workflows/py-publish-fury@test
        with:
          GEMFURY_PUBLISH_TOKEN: ${{ secrets.GEMFURY_PUBLISH_TOKEN }}
