# Normally called when a merge to the main branch happens.
#
# Use this if you just want to have unit-tests + release-please ran to create (pre-)releases.
# does not do anything else; ie: no db, serverless, publishing, etc.
name: Create (Pre-)Release (reusable)
on:
  workflow_call:
    inputs:
      RUN_TESTS:
        required: false
        type: string
        description: Python package we are versioning/deploying; only skips if string is set to 'false' (using string, as composite actions only use strings)
        default: 'true'
  push:
    branches:
      - main
jobs:
  reusable:
    # Depending on if the merge to main was a release merge, or a normal branch merge...
    # it will either create a PR with a release candidate or create a github release object.
    uses: zerapix/reusable-workflows/.github/workflows/py-create-release.yml@test
    secrets: inherit
    with:
      RUN_TESTS: ${{ inputs.RUN_TESTS }}
