# Normally called when a merge to the main branch happens.
on:
  workflow_call:
name: merge-to-main-release-please
concurrency: publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: zerapix/reusable-workflows/all-checkout@main
      - uses: ./.reusable-workflows/py-setup-project
        with:
          GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}
      - uses: ./.reusable-workflows/py-publish-fury
        with:
          GEMFURY_PUBLISH_TOKEN: ${{ secrets.GEMFURY_PUBLISH_TOKEN }}
