# This workflow is used to run unit tests on something that needs an RDS database running.
on:
  workflow_call:
name: Test w/DB
defaults:
  run:
    shell: bash

jobs:
  redirect:
    uses: zerapix/reusable-workflows/.github/workflows/all-test.yml@test
    secrets: inherit
    with:
      runs-on: ${{ inputs.runs-on }}
      need-testing-db: true
      lang: py
