# This workflow is used to run unit tests without a DB.
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
        description: Defaults to x64; specify to use a different runner.

jobs:
  redirect:
    uses: zerapix/reusable-workflows/.github/workflows/all-test.yml@test
    secrets: inherit
    with:
      lang: py
      runs-on: ${{ inputs.runs-on }}
