# This workflow is used to run unit tests without a DB.
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
        description: Defaults to x64; specify to use a different runner.
run-name: Testing pr ${{ github.event.number }} for commit ${{ github.event.after || '*first*' }}
name: Run Tests
jobs:
  redirect:
    uses: zerapix/reusable-workflows/.github/workflows/all-test.yml@z_v2
    secrets: inherit
    with:
      lang: py
      runs-on: ${{ inputs.runs-on }}
