# This workflow is used to run unit tests without a DB.
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
        description: Defaults to x64; specify to use a different runner.
name: Test
jobs:
  test:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: zerapix/reusable-workflows/all-checkout@z_v2
      - uses: ./.reusable-workflows/py-setup-project
        with:
          GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}
      - name: Setup and Test Project
        uses: ./.reusable-workflows/py-run-tests
