# This workflow is used to run unit tests on something that needs an RDS database running.
on:
  workflow_call:
defaults:
  run:
    shell: bash
run-name: Testing pr ${{ github.event.number }} (w/db) for commit ${{ github.event.after || '*first*' }}
name: Run Tests w/DB
jobs:
  redirect:
    uses: zerapix/reusable-workflows/.github/workflows/all-test.yml@z_v2
    secrets: inherit
    with:
      need-testing-db: true
      lang: py
