# This workflow is used to run unit tests without a DB.
on:
  workflow_call:
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: zerapix/reusable-workflows/all-checkout@test
      - name: Setup and Test Project
        uses: ./.reusable-workflows/py-run-tests
        with:
          GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}
