on:
  workflow_call:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-pass
      POSTGRES_DB: unitTestingDB-unit
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    steps:
      #----------------------------------------------
      #       Check-out repo, set-up python + poetry
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: poetry
      - run: poetry install
      #----------------------------------------------
      #         Install dependencies + self
      #----------------------------------------------
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root
      - name: Install Self
        run: poetry install --no-interaction
      #----------------------------------------------
      #         Run test suite
      #----------------------------------------------
      - name: Run tests
        run: poetry run pytest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pg-pass
          POSTGRES_DB: pixyDocsApi-unknown
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
