on:
  workflow_call:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       Check-out repo, set-up python + poetry
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: poetry
      - run: poetry install
      #----------------------------------------------
      #         Install dependencies + self
      #----------------------------------------------
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root
      - name: Install Self
        run: poetry install --no-interaction
      #----------------------------------------------
      #         Run test suite
      #----------------------------------------------
      - name: Run tests
        run: poetry run pytest
